import type { CharacterInput } from "./schema";

const ranger: CharacterInput = {
  version: 1,
  name: "Mira Thornwood",
  system: "dnd-5e-2014",
  paper: "a4",
  identity: [
    { label: "Class & level", value: "Ranger · 3" },
    { label: "Race", value: "Wood elf" },
    { label: "Background", value: "Outlander" },
    { label: "Alignment", value: "Neutral good" },
  ],
  attributes: [
    { label: "Strength", value: 12, modifier: "+1" },
    { label: "Dexterity", value: 16, modifier: "+3" },
    { label: "Constitution", value: 14, modifier: "+2" },
    { label: "Intelligence", value: 10, modifier: "+0" },
    { label: "Wisdom", value: 14, modifier: "+2" },
    { label: "Charisma", value: 8, modifier: "−1" },
  ],
  defenses: [ { label: "Armor class", value: 15 }, { label: "Initiative", value: "+3" }, { label: "Speed", value: "35 ft" }, { label: "Proficiency", value: "+2" }, { label: "Perception", value: 14 } ],
  savingThrows: [
    { name: "Strength", bonus: "+3", proficient: true }, { name: "Dexterity", bonus: "+5", proficient: true },
    { name: "Constitution", bonus: "+2" }, { name: "Intelligence", bonus: "+0" },
    { name: "Wisdom", bonus: "+2" }, { name: "Charisma", bonus: "−1" },
  ],
  skills: [
    { name: "Acrobatics", bonus: "+3" }, { name: "Animal Handling", bonus: "+2" },
    { name: "Arcana", bonus: "+0" }, { name: "Athletics", bonus: "+3", proficient: true },
    { name: "Deception", bonus: "−1" }, { name: "History", bonus: "+0" },
    { name: "Insight", bonus: "+2" }, { name: "Intimidation", bonus: "−1" },
    { name: "Investigation", bonus: "+0" }, { name: "Medicine", bonus: "+2" },
    { name: "Nature", bonus: "+2", proficient: true }, { name: "Perception", bonus: "+4", proficient: true },
    { name: "Performance", bonus: "−1" }, { name: "Persuasion", bonus: "−1" },
    { name: "Religion", bonus: "+0" }, { name: "Sleight of Hand", bonus: "+3" },
    { name: "Stealth", bonus: "+5", proficient: true }, { name: "Survival", bonus: "+4", proficient: true },
  ],
  hitPoints: { maximum: 28, hitDice: "3d10" },
  resources: [{ name: "Inspiration", maximum: 1 }],
  attacks: [
    { name: "Longbow", bonus: "+7", damage: "1d8 + 3 piercing", notes: "Range 150 / 600 ft" },
    { name: "Shortsword", bonus: "+5", damage: "1d6 + 3 piercing", notes: "Finesse · light" },
  ],
  features: [
    { name: "A watchful wanderer", description: "Mira keeps to the old forest roads, guiding travelers past the places where the birds fall silent." },
    { name: "Archery", description: "The supplied longbow attack bonus includes the fighting style bonus." },
    { name: "Field notes", description: "Add your selected subclass features and other rules reminders here." },
  ],
  equipment: ["Longbow & 20 arrows", "Two shortswords", "Studded leather armor", "Explorer’s pack", "Hunting trap", "A pressed silverleaf", "15 gp"],
  proficiencies: ["Light & medium armor, shields", "Simple & martial weapons", "Common, Elvish, Goblin"],
  personality: [
    { label: "Personality", text: "I always sit where I can see the door." },
    { label: "Ideal", text: "The wild belongs to no one." },
    { label: "Bond", text: "Somewhere in the forest, my brother is still alive." },
    { label: "Flaw", text: "I trust tracks more than testimony." },
  ],
  notes: "",
};

export const examples: { id: string; label: string; character: CharacterInput }[] = [
  { id: "2014", label: "D&D 5e · 2014", character: ranger },
  { id: "2024", label: "D&D 5e · 2024", character: {
    version: 1, name: "Rowan Ashford", system: "dnd-5e-2024", paper: "a4",
    identity: [{ label: "Class & level", value: "Wizard · 1" }, { label: "Species", value: "Human" }, { label: "Background", value: "Sage" }],
    attributes: [{ label: "Strength", value: 8, modifier: "−1" }, { label: "Dexterity", value: 14, modifier: "+2" }, { label: "Constitution", value: 14, modifier: "+2" }, { label: "Intelligence", value: 17, modifier: "+3" }, { label: "Wisdom", value: 12, modifier: "+1" }, { label: "Charisma", value: 10, modifier: "+0" }],
    defenses: [{ label: "Armor class", value: 12 }, { label: "Initiative", value: "+2" }, { label: "Speed", value: "30 ft" }, { label: "Proficiency", value: "+2" }],
    hitPoints: { maximum: 8, hitDice: "1d6" },
    savingThrows: [{ name: "Strength", bonus: "−1" }, { name: "Dexterity", bonus: "+2" }, { name: "Constitution", bonus: "+2" }, { name: "Intelligence", bonus: "+5", proficient: true }, { name: "Wisdom", bonus: "+3", proficient: true }, { name: "Charisma", bonus: "+0" }],
    skills: [{ name: "Arcana", bonus: "+5", proficient: true }, { name: "History", bonus: "+5", proficient: true }, { name: "Insight", bonus: "+3", proficient: true }, { name: "Investigation", bonus: "+5", proficient: true }],
    resources: [{ name: "Heroic inspiration", maximum: 1 }],
    equipment: ["Spellbook", "Quarterstaff", "Scholar’s pack", "A sealed letter"],
    features: [{ name: "Character reminders", description: "Add your chosen feats, class features, and rules reminders. This example demonstrates the layout; it is not a complete character build." }],
    spellcasting: { ability: "Intelligence", saveDC: 13, attackBonus: "+5", slots: [{ level: "1st", total: 2 }], spells: [{ name: "Light", level: "Cantrip", description: "Add your spell notes here." }, { name: "Magic Missile", level: "1st", description: "Add your spell notes here." }, { name: "Shield", level: "1st", description: "Add your spell notes here." }] },
    personality: [{ label: "Bond", text: "The letter bears my own handwriting. I have never seen it before." }],
  } },
  { id: "generic", label: "Generic · custom system", character: {
    version: 1, name: "Sable, Keeper of the Last Light", system: "generic", systemName: "The Hollow Coast", paper: "a4",
    identity: [{ label: "Calling", value: "Lighthouse keeper" }, { label: "Origin", value: "The Drowned Isles" }, { label: "Tier", value: "Seasoned" }],
    attributes: [{ label: "Iron", value: 2 }, { label: "Edge", value: 3 }, { label: "Heart", value: 2 }, { label: "Shadow", value: 1 }, { label: "Wits", value: 3 }],
    defenses: [{ label: "Guard", value: 4 }, { label: "Resolve", value: 6 }],
    skills: [{ name: "Navigation", bonus: "+3", proficient: true }, { name: "Mending", bonus: "+2" }, { name: "Reading the sky", bonus: "+3", proficient: true }],
    resources: [{ name: "Light", maximum: 6 }, { name: "Supply", maximum: 5, used: 1 }, { name: "Stress", maximum: 8 }],
    attacks: [{ name: "Harpoon", bonus: "+2", damage: "2 harm", notes: "Close · thrown" }],
    equipment: ["Storm lantern", "Coil of rope", "Salt-stained journal", "Three brass keys"],
    features: [{ name: "Beacon", description: "When the fog closes in, your lantern remembers the way home." }],
    sections: [{ title: "Vows", column: "right", entries: [{ name: "Find the missing lightship", description: "Last seen beyond the eastern shoals, three nights before the storm." }] }, { title: "Companions", column: "middle", entries: [{ name: "Brine", description: "An elderly gull with a talent for finding trouble." }] }],
    personality: [{ label: "Trouble", text: "The sea has started returning things I have lost." }],
  } },
];
